"use client";

import { useEffect, useState } from "react";
import { AlertTriangle, CheckCircle2, Database, LoaderCircle, ShieldCheck, Wrench } from "lucide-react";
import { getAgentCompliance, getAgentTools } from "@/services/api";
import type { ComplianceResponse, ToolDefinition } from "@/types/agent";
import { cn } from "@/lib/utils";

const label = (value: string) => value.replaceAll("_", " ").replace(/\b\w/g, character => character.toUpperCase());

export function ComplianceDashboard() {
  const [compliance, setCompliance] = useState<ComplianceResponse>();
  const [tools, setTools] = useState<ToolDefinition[]>();
  const [error, setError] = useState("");
  useEffect(() => { Promise.all([getAgentCompliance(), getAgentTools()]).then(([matrix, registry]) => { setCompliance(matrix); setTools(registry); }).catch(caught => setError(caught instanceof Error ? caught.message : "The readiness data is unavailable.")); }, []);

  return <section><p className="eyebrow">SIH readiness</p><h1 className="mt-3 text-4xl font-semibold sm:text-5xl">Requirement Compliance</h1><p className="mt-4 max-w-4xl text-sm leading-6 text-zinc-400">A truthful, backend-sourced view of SatQuery AI’s mandatory capabilities, evidence, test coverage, and scientific limitations.</p>
    {!compliance && !error && <p className="mt-7 inline-flex items-center gap-2 text-sm text-zinc-400"><LoaderCircle className="animate-spin" size={17}/>Loading local readiness data…</p>}
    {error && <div role="alert" className="mt-7 rounded-xl border border-rose-300/25 bg-rose-300/[.07] p-4 text-sm text-rose-200">{error}</div>}
    {compliance && <><div className="mt-7 grid gap-4 sm:grid-cols-3"><Summary icon={ShieldCheck} title="Mandatory requirements" value={`${compliance.mandatory_satisfied}/${compliance.mandatory_total}`} note="Backend-declared available"/><Summary icon={Database} title="Execution posture" value="Local" note="No hosted VLM required"/><Summary icon={AlertTriangle} title="Optional absent" value={String(compliance.optional_not_implemented.length)} note={compliance.optional_not_implemented.join(", ") || "None"}/></div>
      <section className="panel mt-7 overflow-hidden"><header className="border-b border-white/[.08] p-5 sm:p-6"><h2 className="text-xl font-semibold">Official requirement matrix</h2><p className="mt-2 text-sm text-zinc-500">Generated {new Date(compliance.generated_at).toLocaleString()}</p></header><div className="max-h-[52rem] overflow-auto"><table className="w-full min-w-[1080px] text-left text-xs"><thead className="sticky top-0 z-10 bg-zinc-950 text-zinc-500"><tr>{["Requirement", "Implementation", "Status", "Tool / model", "Test coverage", "Limitation"].map(item => <th key={item} className="px-4 py-3 font-medium">{item}</th>)}</tr></thead><tbody>{compliance.requirements.map(item => <tr key={item.requirement} className="border-t border-white/[.06] align-top text-zinc-300"><td className="px-4 py-4 font-medium text-zinc-100">{item.requirement}</td><td className="max-w-[260px] px-4 py-4 leading-5">{item.implementation}</td><td className="px-4 py-4"><Status value={item.status}/></td><td className="px-4 py-4 font-mono text-sky-200">{item.tool_or_model}</td><td className="max-w-[220px] px-4 py-4 leading-5">{item.test_coverage}</td><td className="max-w-[300px] px-4 py-4 leading-5 text-zinc-400">{item.limitation}</td></tr>)}</tbody></table></div></section></>}
    {tools && <section className="mt-10"><div className="flex items-center gap-2"><Wrench size={18} className="text-sky-300"/><h2 className="text-2xl font-semibold">Model and Tool Registry</h2></div><p className="mt-2 text-sm text-zinc-500">Unavailable specialists remain visible and are never presented as complete.</p><div className="mt-5 grid gap-4 xl:grid-cols-2">{tools.map(tool => <ToolCard key={tool.id} tool={tool}/>)}</div></section>}
  </section>;
}

function Summary({ icon: Icon, title, value, note }: { icon: typeof ShieldCheck; title: string; value: string; note: string }) { return <article className="panel p-5"><Icon size={18} className="text-sky-300"/><p className="mt-4 text-xs uppercase tracking-wide text-zinc-500">{title}</p><p className="mt-2 text-2xl font-semibold">{value}</p><p className="mt-1 text-xs text-zinc-500">{note}</p></article>; }
function Status({ value }: { value: string }) { const available = value === "available" || value === "optional_available"; return <span className={cn("inline-flex whitespace-nowrap rounded-full border px-2.5 py-1 text-[11px]", available ? "border-emerald-300/25 bg-emerald-300/[.08] text-emerald-200" : "border-amber-300/25 bg-amber-300/[.08] text-amber-100")}>{available ? <CheckCircle2 className="mr-1 inline" size={12}/> : <AlertTriangle className="mr-1 inline" size={12}/>} {label(value)}</span>; }
function ToolCard({ tool }: { tool: ToolDefinition }) { return <article className="panel overflow-hidden"><header className="flex flex-wrap items-start justify-between gap-3 border-b border-white/[.08] p-5"><div><p className="font-mono text-xs text-sky-300">{tool.id}</p><h3 className="mt-2 text-lg font-semibold">{tool.display_name}</h3></div><Status value={tool.status}/></header><div className="space-y-4 p-5 text-sm"><dl className="grid gap-3 sm:grid-cols-2"><Fact name="Tasks" value={tool.supported_tasks.map(label).join(", ")}/><Fact name="Input modes" value={tool.supported_input_modes.map(label).join(", ")}/><Fact name="Modalities" value={tool.supported_modalities.map(label).join(", ")}/><Fact name="Method" value={tool.method_type ?? "Unavailable"}/><Fact name="Remote-sensing adapted" value={tool.remote_sensing_adapted ? "Yes" : "No"}/><Fact name="Service" value={tool.service_path ?? "Not connected"}/><Fact name="Checkpoint" value={tool.checkpoint ?? "Not applicable"}/><Fact name="Adaptation dataset" value={tool.adaptation_dataset ?? "Not applicable"}/></dl>{tool.evidence_outputs.length > 0 && <div><h4 className="text-xs font-semibold uppercase tracking-wide text-zinc-500">Evidence outputs</h4><p className="mt-2 leading-6 text-zinc-300">{tool.evidence_outputs.join(" · ")}</p></div>}<div><h4 className="text-xs font-semibold uppercase tracking-wide text-zinc-500">Truthful scope</h4><p className="mt-2 leading-6 text-zinc-400">{tool.notes}</p></div>{tool.limitations.length > 0 && <details className="rounded-xl border border-white/[.08] p-3"><summary className="cursor-pointer text-sm font-medium">Limitations ({tool.limitations.length})</summary><ul className="mt-3 space-y-2 text-xs leading-5 text-zinc-400">{tool.limitations.map(item => <li key={item}>• {item}</li>)}</ul></details>}</div></article>; }
function Fact({ name, value }: { name: string; value: string }) { return <div><dt className="text-xs text-zinc-500">{name}</dt><dd className="mt-1 break-words leading-5 text-zinc-200">{value}</dd></div>; }
