"use client";

import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
import { useMutation, useQuery } from "@tanstack/react-query";
import { AlertTriangle, Check, CheckCircle2, ChevronDown, ChevronLeft, ChevronRight, ChevronUp, Clock3, Download, FileArchive, FileJson, FileText, GitBranch, GitCompareArrows, Images, LoaderCircle, RefreshCcw, X } from "lucide-react";
import { agentArtifactUrl, agentPreviewUrl, assessComparison, generateComparisonReport, getComparisonItem, getComparisonItems } from "@/services/api";
import type { ComparisonAssessment, ComparisonItem, ComparisonItemSummary, ComparisonPreview } from "@/types/agent";
import { comparisonTaskLabel, factualDifferences, scalarEntries } from "@/lib/mission-comparison";
import { MissionImageComparisonViewer } from "@/components/mission-image-comparison-viewer";
import { hasPresentationComparisonReturn, readPresentationComparisonRequestIds } from "@/lib/presentation-comparison";
import { PresentationReturnBanner } from "@/components/presentation-page-handoff";

const statusTone: Record<string, string> = { success: "border-emerald-300/20 bg-emerald-400/[.08] text-emerald-200", partial: "border-amber-300/20 bg-amber-300/[.07] text-amber-100", alignment_required: "border-amber-300/20 bg-amber-300/[.07] text-amber-100", failed: "border-rose-300/20 bg-rose-300/[.07] text-rose-100" };
const nice = (value: string) => value.replaceAll("_", " ").replace(/\b\w/g, letter => letter.toUpperCase());
const time = (value: string) => new Date(value).toLocaleString([], { dateStyle: "medium", timeStyle: "short" });

function ResultCard({ item, selected, limitReached, onToggle, onOpen }: { item: ComparisonItemSummary; selected: boolean; limitReached: boolean; onToggle: () => void; onOpen: () => void }) {
  return <article className={`panel overflow-hidden transition ${selected ? "ring-2 ring-sky-300/60" : ""}`}><button type="button" aria-pressed={selected} disabled={!selected && limitReached} onClick={onToggle} className="block w-full text-left disabled:cursor-not-allowed disabled:opacity-45"><div className="relative aspect-[16/8] bg-zinc-950/60">{item.thumbnail ? <img src={agentPreviewUrl(item.thumbnail.url)} alt={`${item.display_name} thumbnail`} className="h-full w-full object-cover"/> : <div className="grid h-full place-items-center text-zinc-600"><Images size={24}/></div>}<span className={`absolute right-3 top-3 grid h-7 w-7 place-items-center rounded-full border ${selected ? "border-sky-200 bg-sky-300 text-zinc-950" : "border-white/20 bg-black/60 text-transparent"}`}><Check size={15}/></span></div><div className="p-4"><div className="flex items-center justify-between gap-3"><h3 className="truncate text-sm font-semibold">{item.display_name}</h3><span className={`shrink-0 rounded-full border px-2 py-1 text-[10px] ${statusTone[item.status] ?? "border-white/10 text-zinc-400"}`}>{nice(item.status)}</span></div><p className="mt-2 text-xs text-zinc-500">{time(item.created_at)} · {nice(item.input_mode)}</p><p className="mt-1 text-xs text-zinc-500">{item.modalities.map(nice).join(" + ") || "Modality unavailable"}</p><div className="mt-3 flex flex-wrap gap-1.5 text-[10px]"><span className="rounded-full bg-white/[.05] px-2 py-1">{item.execution_duration_ms == null ? "Runtime unavailable" : `${item.execution_duration_ms} ms`}</span><span className="rounded-full bg-white/[.05] px-2 py-1">{item.cached ? "Cached" : "Fresh"}</span><span className="rounded-full bg-white/[.05] px-2 py-1">{item.report_available ? "Report available" : "No report"}</span></div></div></button><button onClick={onOpen} className="w-full border-t border-white/[.07] px-4 py-2.5 text-left text-xs text-sky-200 hover:bg-sky-400/[.06]">Open result detail</button></article>;
}

function EvidenceCarousel({ values, name }: { values: ComparisonPreview[]; name: string }) {
  const [index, setIndex] = useState(0); const safe = Math.min(index, Math.max(0, values.length - 1)); const current = values[safe];
  if (!current) return <div className="grid min-h-48 place-items-center rounded-xl bg-zinc-950/45 text-sm text-zinc-600">No image product</div>;
  return <figure className="overflow-hidden rounded-xl border border-white/[.08] bg-zinc-950/45"><div className="relative grid aspect-video place-items-center"><img src={agentPreviewUrl(current.url)} alt={`${name}: ${current.label}`} className="h-full w-full object-contain"/><div className="absolute bottom-2 right-2 flex gap-1"><button onClick={() => setIndex(value => (value - 1 + values.length) % values.length)} aria-label={`Previous ${name} evidence`} className="rounded-lg bg-black/70 p-2 text-white"><ChevronLeft size={14}/></button><button onClick={() => setIndex(value => (value + 1) % values.length)} aria-label={`Next ${name} evidence`} className="rounded-lg bg-black/70 p-2 text-white"><ChevronRight size={14}/></button></div></div><figcaption className="flex justify-between px-3 py-2 text-xs text-zinc-500"><span>{current.label}</span><span>{safe + 1}/{values.length}</span></figcaption></figure>;
}

function Section({ title, items, children }: { title: string; items: ComparisonItem[]; children: (item: ComparisonItem) => React.ReactNode }) {
  return <section><h3 className="mb-3 text-xs font-semibold uppercase tracking-[.14em] text-zinc-500">{title}</h3><div className={`grid gap-3 ${items.length === 2 ? "lg:grid-cols-2" : items.length === 3 ? "xl:grid-cols-3" : "xl:grid-cols-4"}`}>{items.map(item => <article key={item.request_id} className="glass min-w-0 rounded-xl p-4">{children(item)}</article>)}</div></section>;
}

function RecordView({ value }: { value: Record<string, unknown> }) {
  const entries = scalarEntries(value);
  return entries.length ? <dl className="space-y-2 text-xs">{entries.map(([name, content]) => <div key={name} className="flex justify-between gap-3 border-b border-white/[.05] pb-2"><dt className="capitalize text-zinc-500">{name}</dt><dd className="max-w-[55%] break-words text-right text-zinc-300">{content}</dd></div>)}</dl> : <p className="text-sm text-zinc-600">Unavailable</p>;
}

function Lineage({ item }: { item: ComparisonItem }) {
  return <div className="flex flex-wrap items-center gap-2">{item.lineage.map((node, index) => <div key={`${node.kind}-${index}`} className="contents"><span className="rounded-lg border border-sky-300/15 bg-sky-300/[.05] px-3 py-2 text-xs"><span className="block text-[9px] uppercase tracking-wide text-zinc-500">{nice(node.kind)}</span>{node.label}</span>{index < item.lineage.length - 1 && <span className="text-zinc-600">→</span>}</div>)}</div>;
}

function DetailDialog({ item, onClose }: { item: ComparisonItem; onClose: () => void }) {
  return <div className="fixed inset-0 z-[80] grid place-items-center bg-black/70 p-4" role="dialog" aria-modal="true" aria-label={`${item.display_name} result detail`}><article className="panel max-h-[90dvh] w-full max-w-3xl overflow-y-auto p-5 sm:p-7"><div className="flex justify-between gap-4"><div><p className="eyebrow">Stored result</p><h2 className="mt-2 text-2xl font-semibold">{item.display_name}</h2><p className="mt-2 font-mono text-xs text-zinc-500">{item.request_id}</p></div><button onClick={onClose} aria-label="Close result detail" className="h-fit rounded-lg p-2 hover:bg-white/10"><X size={18}/></button></div><div className="mt-6"><EvidenceCarousel values={[...item.input_previews, ...item.output_previews]} name={item.display_name}/></div><div className="mt-6 grid gap-5 sm:grid-cols-2"><div><h3 className="text-sm font-semibold">Statistics</h3><div className="mt-3"><RecordView value={item.statistics}/></div></div><div><h3 className="text-sm font-semibold">Provenance</h3><div className="mt-3"><RecordView value={item.provenance}/></div></div></div><div className="mt-6"><h3 className="text-sm font-semibold">Lineage</h3><div className="mt-3"><Lineage item={item}/></div></div></article></div>;
}

export function MissionComparisonWorkspace() {
  const history = useQuery({ queryKey: ["mission-comparison-items"], queryFn: ({ signal }) => getComparisonItems(signal), retry: 1 });
  const [selected, setSelected] = useState<string[]>([]); const [taskFilter, setTaskFilter] = useState("all"); const [statusFilter, setStatusFilter] = useState("all"); const [sort, setSort] = useState("newest"); const [comparison, setComparison] = useState<{ items: ComparisonItem[]; assessment: ComparisonAssessment }>(); const [detail, setDetail] = useState<ComparisonItem>(); const [note, setNote] = useState(""); const [researchOpen, setResearchOpen] = useState(false);
  useEffect(() => {
    if (!hasPresentationComparisonReturn(window.sessionStorage)) return;
    const requestIds = readPresentationComparisonRequestIds(window.sessionStorage);
    if (requestIds.length === 2) setSelected(requestIds);
  }, []);
  const compare = useMutation({ mutationFn: async (ids: string[]) => ({ items: await Promise.all(ids.map(id => getComparisonItem(id))), assessment: await assessComparison(ids) }), onSuccess: setComparison });
  const open = useMutation({ mutationFn: (requestId: string) => getComparisonItem(requestId), onSuccess: setDetail });
  const report = useMutation({ mutationFn: () => comparison ? generateComparisonReport(comparison.items.map(item => item.request_id), note) : Promise.reject(new Error("Compare results before generating a report.")), onSuccess: () => void history.refetch() });
  const tasks = useMemo(() => Array.from(new Set((history.data ?? []).map(item => item.task))), [history.data]);
  const visible = useMemo(() => (history.data ?? []).filter(item => (taskFilter === "all" || item.task === taskFilter) && (statusFilter === "all" || item.status === statusFilter)).sort((left, right) => sort === "newest" ? +new Date(right.created_at) - +new Date(left.created_at) : sort === "oldest" ? +new Date(left.created_at) - +new Date(right.created_at) : (left.execution_duration_ms ?? Number.MAX_SAFE_INTEGER) - (right.execution_duration_ms ?? Number.MAX_SAFE_INTEGER)), [history.data, sort, statusFilter, taskFilter]);
  const toggle = (id: string) => setSelected(value => value.includes(id) ? value.filter(item => item !== id) : value.length < 4 ? [...value, id] : value);
  const facts = comparison ? factualDifferences(comparison.items, comparison.assessment.assessments) : [];
  const viewerImages = comparison?.items.map(item => ({ ...(item.output_previews[0] ?? item.input_previews[0]), requestId: item.request_id, resultName: item.display_name })).filter((item): item is ComparisonPreview & { requestId: string; resultName: string } => Boolean(item.url)) ?? [];
  return <section aria-labelledby="mission-comparison-title"><PresentationReturnBanner route="/assistant/compare"/><div className="flex flex-wrap items-start justify-between gap-5"><div><p className="eyebrow">Authoritative stored results</p><h1 id="mission-comparison-title" className="mt-3 text-4xl font-semibold sm:text-5xl">Mission Comparison</h1><p className="mt-4 max-w-4xl text-sm leading-6 text-zinc-400">Compare two to four recent SatQuery workflows without re-uploading or rerunning data. Content hashes—not filenames—establish shared input identity.</p></div><button onClick={() => history.refetch()} disabled={history.isFetching} className="inline-flex items-center gap-2 rounded-xl border border-white/[.1] px-3 py-2 text-sm text-zinc-300"><RefreshCcw size={15} className={history.isFetching ? "animate-spin" : ""}/>Refresh</button></div>
    {history.isLoading && <div className="mt-8 flex items-center gap-2 text-sm text-zinc-400"><LoaderCircle className="animate-spin" size={17}/>Loading recent authoritative results…</div>}
    {history.error && <div className="mt-8 rounded-xl border border-rose-300/20 bg-rose-300/[.07] p-5"><h2 className="font-semibold text-rose-100">Backend offline</h2><p className="mt-2 text-sm text-rose-100/80">Mission history could not be loaded. Confirm the local backend is running, then retry.</p></div>}
    {history.data && history.data.length === 0 && <div className="panel mt-8 max-w-3xl p-8 text-center"><GitCompareArrows className="mx-auto text-zinc-600" size={28}/><h2 className="mt-4 text-lg font-semibold">No comparison results yet</h2><p className="mt-2 text-sm text-zinc-500">Run workflows in SatQuery Assistant to populate comparison results.</p><Link href="/assistant" className="mt-5 inline-flex rounded-xl bg-sky-300 px-4 py-2.5 text-sm font-semibold text-zinc-950">Open SatQuery Assistant</Link></div>}
    {history.data && history.data.length > 0 && <><section className="panel mt-8 p-4 sm:p-5"><div className="grid gap-3 sm:grid-cols-3"><label className="text-xs text-zinc-500">Filter by task<select value={taskFilter} onChange={event => setTaskFilter(event.target.value)} className="mt-2 block w-full rounded-xl border border-white/[.1] bg-zinc-950/50 px-3 py-2.5 text-sm text-zinc-200"><option value="all">All tasks</option>{tasks.map(task => <option key={task} value={task}>{comparisonTaskLabel(task)}</option>)}</select></label><label className="text-xs text-zinc-500">Filter by status<select value={statusFilter} onChange={event => setStatusFilter(event.target.value)} className="mt-2 block w-full rounded-xl border border-white/[.1] bg-zinc-950/50 px-3 py-2.5 text-sm text-zinc-200"><option value="all">All statuses</option>{["success", "partial", "alignment_required", "failed"].map(value => <option key={value}>{value}</option>)}</select></label><label className="text-xs text-zinc-500">Sort<select value={sort} onChange={event => setSort(event.target.value)} className="mt-2 block w-full rounded-xl border border-white/[.1] bg-zinc-950/50 px-3 py-2.5 text-sm text-zinc-200"><option value="newest">Newest</option><option value="oldest">Oldest</option><option value="runtime">Runtime</option></select></label></div><div className="mt-4 flex flex-wrap items-center justify-between gap-3"><p className="text-sm text-zinc-400">{selected.length}/4 selected {selected.length === 4 && <span className="text-amber-200">· Selection limit reached</span>}</p><div className="flex gap-2"><button onClick={() => { setSelected([]); setComparison(undefined); }} className="rounded-xl border border-white/[.1] px-3 py-2 text-sm text-zinc-400">Clear selection</button><button onClick={() => compare.mutate(selected)} disabled={selected.length < 2 || compare.isPending} className="inline-flex items-center gap-2 rounded-xl bg-sky-300 px-4 py-2 text-sm font-semibold text-zinc-950 disabled:opacity-40">{compare.isPending ? <LoaderCircle className="animate-spin" size={16}/> : <GitCompareArrows size={16}/>}Compare selected</button></div></div></section><div className="mt-5 grid gap-4 sm:grid-cols-2 xl:grid-cols-3 2xl:grid-cols-4">{visible.map(item => <ResultCard key={item.request_id} item={item} selected={selected.includes(item.request_id)} limitReached={selected.length >= 4} onToggle={() => toggle(item.request_id)} onOpen={() => open.mutate(item.request_id)}/>)}</div>{visible.length === 0 && <p className="mt-8 text-center text-sm text-zinc-500">No stored results match these filters.</p>}</>}
    {(compare.error || open.error) && <div className="mt-5 rounded-xl border border-amber-300/20 bg-amber-300/[.06] p-4 text-sm text-amber-100">The selected result is stale, expired, or unavailable. Refresh the history and select an active result.</div>}
    {comparison && <div className="mt-12 space-y-7"><div><p className="eyebrow">Authoritative comparison</p><h2 className="mt-2 text-3xl font-semibold">Summary</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-zinc-500">Comparability and differences come from stored backend results. Runtime is never treated as scientific accuracy, and no universal winner is inferred.</p></div><section aria-labelledby="shared-inputs-title"><h3 id="shared-inputs-title" className="mb-3 text-sm font-semibold">Shared Inputs &amp; Comparability</h3><div className="grid gap-3 md:grid-cols-2">{comparison.assessment.assessments.map(value => <article key={`${value.left_request_id}-${value.right_request_id}`} className={`rounded-2xl border p-5 ${value.level === "direct" ? "border-emerald-300/20 bg-emerald-400/[.06]" : value.level === "partial" ? "border-amber-300/20 bg-amber-300/[.06]" : "border-rose-300/20 bg-rose-300/[.06]"}`}><div className="flex flex-wrap items-center justify-between gap-2"><div className="flex items-center gap-2">{value.level === "direct" ? <CheckCircle2 size={16} className="text-emerald-300"/> : <AlertTriangle size={16} className={value.level === "partial" ? "text-amber-200" : "text-rose-200"}/>}<h3 className="text-sm font-semibold">{nice(value.level)}</h3></div><div className="flex gap-1.5 text-[10px]"><span className="rounded-full bg-white/[.05] px-2 py-1">Shared input: {value.shared_inputs ? "Yes" : "No"}</span><span className="rounded-full bg-white/[.05] px-2 py-1">Task family: {value.shared_task_family ? "Shared" : "Different"}</span></div></div><p className="mt-3 text-sm leading-6 text-zinc-400">{value.reason}</p>{value.warnings.map(warning => <p key={warning} className="mt-2 text-xs text-amber-100">{warning}</p>)}</article>)}</div></section>
      <section className="panel overflow-hidden"><header className="border-b border-white/[.08] p-5"><h2 className="font-semibold">Key Differences</h2><p className="mt-1 text-xs text-zinc-500">Labels identify observable differences only; no universal winner is inferred.</p></header><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-xs"><thead><tr><th className="px-4 py-3 text-zinc-500">Fact</th>{comparison.items.map(item => <th key={item.request_id} className="px-4 py-3">{item.display_name}</th>)}</tr></thead><tbody>{facts.map(fact => <tr key={fact.label} className="border-t border-white/[.06]"><th className="px-4 py-3 font-medium text-zinc-400">{fact.label}{fact.caution && <span className="mt-1 block font-normal text-[10px] text-amber-100">{fact.caution}</span>}</th>{comparison.items.map(item => <td key={item.request_id} className="px-4 py-3 text-zinc-300">{fact.values[item.request_id]}</td>)}</tr>)}</tbody></table></div></section>
      <Section title="Changed Statistics" items={comparison.items}>{item => <dl className="space-y-2 text-xs">{scalarEntries(item.statistics).slice(0, 6).map(([name, content]) => <div key={name} className="flex justify-between gap-3 border-b border-white/[.05] pb-2"><dt className="capitalize text-zinc-500">{name}</dt><dd className="max-w-[55%] break-words text-right text-zinc-300">{content}</dd></div>)}{scalarEntries(item.statistics).length === 0 && <div className="text-zinc-600">No scalar statistics published.</div>}</dl>}</Section>
      <button type="button" onClick={() => setResearchOpen(value => !value)} aria-expanded={researchOpen} className="result-audit-toggle"><span><span className="result-section-number">RESEARCH</span><strong>Comparison audit</strong><small>Answers, full statistics, provenance, tools, limitations, and lineage.</small></span>{researchOpen ? <ChevronUp size={20}/> : <ChevronDown size={20}/>}</button>
      {researchOpen && <div className="space-y-7"><Section title="Result identity" items={comparison.items}>{item => <><h3 className="font-semibold">{item.display_name}</h3><p className="mt-2 font-mono text-[10px] text-zinc-500">{item.request_id}</p><p className="mt-3 text-xs text-zinc-400">{time(item.created_at)} · {nice(item.status)}</p></>}</Section>
      <Section title="Input previews" items={comparison.items}>{item => <EvidenceCarousel values={item.input_previews} name={`${item.display_name} input`}/>}</Section>
      <Section title="Outputs and evidence" items={comparison.items}>{item => <EvidenceCarousel values={item.output_previews} name={`${item.display_name} output`}/>}</Section>
      <Section title="Answer" items={comparison.items}>{item => <p className="text-sm leading-6 text-zinc-300">{item.answer ?? "No textual output was produced by this workflow."}</p>}</Section>
      <Section title="Key statistics" items={comparison.items}>{item => <RecordView value={item.statistics}/>}</Section>
      <Section title="Confidence" items={comparison.items}>{item => <><p className="text-sm font-medium">{nice(String(item.confidence.level ?? "unavailable"))}</p><p className="mt-2 text-xs leading-5 text-zinc-500">{String(item.confidence.reason ?? "No confidence basis reported.")}</p></>}</Section>
      <Section title="Runtime and device" items={comparison.items}>{item => <div className="space-y-3 text-sm"><p className="flex items-center gap-2"><Clock3 size={15} className="text-sky-200"/>{item.execution_duration_ms == null ? "Unavailable" : `${item.execution_duration_ms.toLocaleString()} ms`}</p><p className="text-zinc-500">Device: {item.device ?? "Not reported"}</p></div>}</Section>
      <Section title="Selected tools" items={comparison.items}>{item => <div className="flex flex-wrap gap-2">{item.selected_tools.map(tool => <span key={tool} className="rounded-lg bg-sky-400/[.08] px-2 py-1 font-mono text-[10px] text-sky-200">{tool}</span>)}</div>}</Section>
      <Section title="Provenance" items={comparison.items}>{item => <RecordView value={item.provenance}/>}</Section>
      <Section title="Limitations and warnings" items={comparison.items}>{item => <div className="space-y-3 text-xs leading-5 text-zinc-400">{item.limitations.map(value => <p key={value}>• {value}</p>)}{item.warnings.map(value => <p key={value} className="text-amber-100">⚠ {value}</p>)}{!item.limitations.length && !item.warnings.length && <p>No additional limitations or warnings were stored.</p>}</div>}</Section>
      <section className="panel p-5"><h3 className="flex items-center gap-2 font-semibold"><GitBranch size={17} className="text-sky-200"/>Supported lineage</h3><div className="mt-5 space-y-5">{comparison.items.map(item => <div key={item.request_id}><p className="mb-2 text-xs font-medium text-zinc-400">{item.display_name}</p><Lineage item={item}/></div>)}</div></section></div>}
      <section><div className="mb-3"><p className="eyebrow">Visual inspection</p><h2 className="mt-2 text-2xl font-semibold">Compare Images</h2></div><MissionImageComparisonViewer images={viewerImages} assessments={comparison.assessment.assessments}/></section>
      <section className="panel p-5 sm:p-7"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="eyebrow">Backend-authoritative export</p><h2 className="mt-2 text-xl font-semibold">Reports</h2><p className="mt-2 max-w-2xl text-sm text-zinc-500">PDF, JSON, and ZIP use the stored backend items—not browser-supplied statistics.</p></div><button onClick={() => report.mutate()} disabled={report.isPending} className="inline-flex items-center gap-2 rounded-xl bg-sky-300 px-4 py-2.5 text-sm font-semibold text-zinc-950 disabled:opacity-40">{report.isPending ? <LoaderCircle className="animate-spin" size={16}/> : <FileText size={16}/>}Generate report</button></div><label className="mt-5 block text-xs text-zinc-500">User note · optional<textarea value={note} maxLength={2000} onChange={event => setNote(event.target.value)} placeholder="Clearly labelled as a user-authored comparison note." className="mt-2 min-h-24 w-full rounded-xl border border-white/[.1] bg-zinc-950/40 p-3 text-sm text-zinc-200 outline-none focus:border-sky-300/40"/></label>{report.error && <p className="mt-3 text-sm text-rose-200">{report.error.message}</p>}{report.data && <div className="mt-5 flex flex-wrap gap-2">{report.data.artifacts.map(artifact => <a key={artifact.format} href={agentArtifactUrl(artifact.url)} download className="inline-flex items-center gap-2 rounded-xl border border-sky-300/25 px-3 py-2 text-sm text-sky-200">{artifact.format === "pdf" ? <FileText size={15}/> : artifact.format === "json" ? <FileJson size={15}/> : <FileArchive size={15}/>}Download {artifact.format.toUpperCase()} <Download size={13}/></a>)}</div>}</section>
    </div>}
    {detail && <DetailDialog item={detail} onClose={() => setDetail(undefined)}/>}<span className="sr-only" aria-live="polite">{open.isPending ? "Loading result detail" : compare.isPending ? "Loading comparison" : report.isPending ? "Generating comparison report" : ""}</span>
  </section>;
}
