"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import { Activity, AlertTriangle, CheckCircle2, Cpu, Database, ExternalLink, Wrench } from "lucide-react";
import type { AgentHealth, AnalyticsResponse, ToolDefinition } from "@/types/agent";
import { architectureLabel } from "@/lib/architecture";
import { formatAnalyticsDuration } from "@/lib/analytics";
import { cn } from "@/lib/utils";

export function SpecialistInspector({ tools, analytics, health }: { tools: ToolDefinition[]; analytics: AnalyticsResponse; health: AgentHealth }) {
  const [selectedId, setSelectedId] = useState(tools[0]?.id ?? "");
  const inspectorRef = useRef<HTMLElement>(null);
  useEffect(() => { if (!tools.some(tool => tool.id === selectedId)) setSelectedId(tools[0]?.id ?? ""); }, [tools, selectedId]);
  const selected = tools.find(tool => tool.id === selectedId);
  const runtimeById = useMemo(() => Object.fromEntries(analytics.tools.map(tool => [tool.id, tool])), [analytics.tools]);
  const runtime = selected ? runtimeById[selected.id] : undefined;
  const select = (id: string) => { setSelectedId(id); requestAnimationFrame(() => inspectorRef.current?.focus({ preventScroll: true })); };

  return <section aria-labelledby="specialist-explorer-title"><div><p className="eyebrow">Registry sourced · unavailable tools remain visible</p><h2 id="specialist-explorer-title" className="mt-2 text-2xl font-semibold">Specialist Explorer</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-zinc-500">Inspect declared scope, provenance, live lifecycle, evidence products, and limitations without loading a model.</p></div>
    <div className="mt-6 grid gap-5 2xl:grid-cols-[1.05fr_.95fr]"><div className="grid content-start gap-3 sm:grid-cols-2">{tools.map(tool => { const active = tool.id === selectedId; const item = runtimeById[tool.id]; return <button key={tool.id} type="button" aria-pressed={active} onClick={() => select(tool.id)} className={cn("panel p-4 text-left transition focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-sky-300", active ? "border-sky-300/45 bg-sky-300/[.07]" : "hover:border-sky-300/20")}><div className="flex items-start justify-between gap-3"><span className="grid h-9 w-9 place-items-center rounded-xl bg-sky-300/[.07] text-sky-300"><Wrench size={16}/></span><Status value={tool.status}/></div><h3 className="mt-3 text-sm font-semibold text-zinc-100">{tool.display_name}</h3><p className="mt-1 font-mono text-[10px] text-sky-300">{tool.id}</p><div className="mt-3 flex flex-wrap gap-1.5"><Tag>{tool.supported_input_modes.map(architectureLabel).join(" · ")}</Tag><Tag>{tool.supported_modalities.map(architectureLabel).join(" · ")}</Tag></div><p className="mt-3 text-[11px] text-zinc-500">Lifecycle: {architectureLabel(item?.lifecycle_status ?? "registered")} · Runtime: {formatAnalyticsDuration(item?.last_runtime_ms ?? null)}</p></button>; })}</div>
      {selected && <article ref={inspectorRef} tabIndex={-1} aria-live="polite" className="panel self-start overflow-hidden focus:outline-none 2xl:sticky 2xl:top-6"><header className="border-b border-white/[.08] p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-mono text-xs text-sky-300">{selected.id}</p><h3 className="mt-2 text-xl font-semibold">{selected.display_name}</h3></div><Status value={selected.status}/></div><p className="mt-3 text-sm leading-6 text-zinc-400">{selected.notes}</p></header><div className="space-y-5 p-5"><dl className="grid gap-4 sm:grid-cols-2"><Fact icon={Activity} name="Tasks" value={selected.supported_tasks.map(architectureLabel).join(", ")}/><Fact icon={Wrench} name="Method" value={selected.method_type ?? "Service-level implementation"}/><Fact icon={Cpu} name="Lifecycle / device" value={`${architectureLabel(runtime?.lifecycle_status ?? health.specialists[selected.id]?.status ?? "registered")} · ${runtime?.device ?? health.specialists[selected.id]?.device ?? "No device reported"}`}/><Fact icon={Activity} name="Last runtime" value={formatAnalyticsDuration(runtime?.last_runtime_ms ?? null)}/><Fact icon={Database} name="Checkpoint" value={selected.checkpoint ?? "Not applicable"}/><Fact icon={Database} name="Adaptation dataset" value={selected.adaptation_dataset ?? "Not applicable"}/></dl><div><h4 className="text-xs font-semibold uppercase tracking-wide text-zinc-500">Remote-sensing adaptation</h4><p className="mt-2 text-sm text-zinc-300">{selected.remote_sensing_adapted ? "Yes — declared by the registry." : "No — no remote-sensing fine-tuning is claimed."}</p></div><div><h4 className="text-xs font-semibold uppercase tracking-wide text-zinc-500">Evidence outputs</h4>{selected.evidence_outputs.length ? <ul className="mt-2 grid gap-2 text-sm text-zinc-400 sm:grid-cols-2">{selected.evidence_outputs.map(item => <li key={item} className="rounded-lg border border-white/[.06] p-2.5">{item}</li>)}</ul> : <p className="mt-2 text-sm text-zinc-500">No evidence products declared in the registry.</p>}</div><div><h4 className="text-xs font-semibold uppercase tracking-wide text-zinc-500">Limitations</h4>{selected.limitations.length ? <ul className="mt-2 space-y-2 text-sm leading-6 text-zinc-400">{selected.limitations.map(item => <li key={item}>• {item}</li>)}</ul> : <p className="mt-2 text-sm text-zinc-500">No specialist-specific limitation list is published; see the scope note above.</p>}</div>{selected.source && <a href={selected.source} target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 text-xs text-sky-300 hover:text-sky-200">Public provenance source <ExternalLink size={13}/></a>}</div></article>}
    </div>
  </section>;
}

function Status({ value }: { value: string }) { const okay = value === "available"; return <span className={cn("inline-flex items-center gap-1 rounded-full border px-2 py-1 text-[10px]", okay ? "border-emerald-300/25 bg-emerald-300/[.07] text-emerald-200" : "border-amber-300/25 bg-amber-300/[.07] text-amber-100")}>{okay ? <CheckCircle2 size={11}/> : <AlertTriangle size={11}/>} {architectureLabel(value)}</span>; }
function Tag({ children }: { children: React.ReactNode }) { return <span className="rounded-full border border-white/[.07] px-2 py-1 text-[10px] text-zinc-500">{children}</span>; }
function Fact({ icon: Icon, name, value }: { icon: typeof Activity; name: string; value: string }) { return <div><dt className="flex items-center gap-1.5 text-xs text-zinc-500"><Icon size={12}/>{name}</dt><dd className="mt-1.5 break-words text-sm leading-5 text-zinc-200">{value}</dd></div>; }
